### ISSUE TITLE
Crash with unburied summons

### ISSUE THREAD

**Issue by WinDanesz** [WinDanesz/WizardryNecromancersDelight#2]
```Description: Ticking entity

java.lang.ClassCastException: com.Fishmod.mod_LavaCow.entities.tameable.EntityUnburied cannot be cast to electroblob.wizardry.entity.living.EntityZombieMinion
	at com.windanesz.necromancersdelight.handler.NDEventHandler.onLivingSpawnEvent(NDEventHandler.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_558_NDEventHandler_onLivingSpawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at com.windanesz.necromancersdelight.handler.NDEventHandler.onLivingSpawnEvent(NDEventHandler.java:298)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_558_NDEventHandler_onLivingSpawnEvent_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1209)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at electroblob.wizardry.entity.construct.EntityZombieSpawner.func_70071_h_(EntityZombieSpawner.java:57)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by WinDanesz** [comment]
Also happens for weta 
```
java.lang.ClassCastException: com.Fishmod.mod_LavaCow.entities.tameable.EntityWeta cannot be cast to electroblob.wizardry.entity.living.EntityZombieMinion
```
